package gcode

import (
	"bufio"
	"fmt"
	"io"
	"math"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// Option configures a Parser.
type Option func(*options)

type options struct {
	onLayerComplete func(layer int, usage FilamentUsage)
}

// WithLayerHook registers a callback fired after each layer is fully parsed.
//
// The hook runs synchronously on the parser goroutine: a slow callback will
// block parsing and the parser does not recover panics. Keep the callback
// cheap and non-blocking.
func WithLayerHook(fn func(layer int, usage FilamentUsage)) Option {
	return func(o *options) {
		o.onLayerComplete = fn
	}
}

// Parser parses OrcaSlicer gcode files.
type Parser struct {
	opts options
}

// New creates a Parser with the given options.
func New(opts ...Option) *Parser {
	p := &Parser{}
	for _, o := range opts {
		o(&p.opts)
	}
	return p
}

// ParseFile parses the gcode file at path.
func (p *Parser) ParseFile(path string) (*PrintFile, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return p.Parse(f)
}

// Parse parses gcode from r.
func (p *Parser) Parse(r io.Reader) (*PrintFile, error) {
	return parse(r, p.opts)
}

// ParseFile is a package-level convenience function.
func ParseFile(path string) (*PrintFile, error) { return New().ParseFile(path) }

// Parse is a package-level convenience function.
func Parse(r io.Reader) (*PrintFile, error) { return New().Parse(r) }

// ---- internal parser state ----

type parserState int

const (
	stateInit parserState = iota
	stateHeader
	stateIdle
	stateConfig
	stateStartup
	stateLayer
	stateFooter
)

type extrusionMode int

const (
	extAbsolute extrusionMode = iota
	extRelative
)

var (
	reGeneratedBy = regexp.MustCompile(`^; generated by (\S+) (\S+) on (.+)$`)
	reLayerMarker = regexp.MustCompile(`^; layer num/total_layer_count:\s*(\d+)/(\d+)`)
	reEParam      = regexp.MustCompile(`E(-?[0-9]*\.?[0-9]+)`)
	reG92E        = regexp.MustCompile(`^G92\s+.*E(-?[0-9]*\.?[0-9]+)`)
)

func parse(r io.Reader, opts options) (*PrintFile, error) {
	pf := &PrintFile{}
	state := stateInit
	headerFound := false

	var (
		extMode      extrusionMode = extAbsolute
		ePosition    float64
		accumulator  float64
		currentLayer int
	)

	flush := func() {
		usage := convertToFilamentUsage(accumulator, pf.Metadata.FilamentDiameter, pf.Metadata.FilamentDensity)
		if state == stateStartup {
			pf.StartupUsage = usage
		} else if state == stateLayer {
			pf.Layers = append(pf.Layers, LayerUsage{Number: currentLayer, Usage: usage})
			if opts.onLayerComplete != nil {
				opts.onLayerComplete(currentLayer, usage)
			}
		}
		accumulator = 0
	}

	scanner := bufio.NewScanner(r)
	// Increase buffer for very long lines
	buf := make([]byte, 1024*1024)
	scanner.Buffer(buf, len(buf))

	for scanner.Scan() {
		line := scanner.Text()

		// Block boundary markers — checked first regardless of state
		switch {
		case line == "; HEADER_BLOCK_START":
			headerFound = true
			state = stateHeader
			continue
		case line == "; HEADER_BLOCK_END":
			state = stateIdle
			continue
		case line == "; CONFIG_BLOCK_START":
			state = stateConfig
			continue
		case line == "; CONFIG_BLOCK_END":
			state = stateIdle
			continue
		case line == "; EXECUTABLE_BLOCK_START":
			state = stateStartup
			extMode = extAbsolute
			ePosition = 0
			accumulator = 0
			continue
		case line == "; EXECUTABLE_BLOCK_END":
			if state == stateStartup || state == stateLayer {
				flush()
			}
			state = stateFooter
			continue
		}

		// Reject unsupported real tool changes (T1–T9). Bambu-specific
		// multi-digit preset codes like T1000 / T255 are intentionally ignored.
		if tok, bad := unsupportedToolChange(line); bad {
			return nil, fmt.Errorf("gcode: multi-filament file not supported (tool change %s)", tok)
		}

		switch state {
		case stateHeader:
			parseHeaderLine(line, &pf.Metadata)

		case stateConfig:
			if err := parseConfigLine(line, &pf.Config); err != nil {
				return nil, err
			}

		case stateStartup, stateLayer:
			// Layer marker transition — checked on raw line (it is a comment).
			if m := reLayerMarker.FindStringSubmatch(line); m != nil {
				layerNum, _ := strconv.Atoi(m[1])
				flush()
				state = stateLayer
				currentLayer = layerNum
				accumulator = 0
				continue
			}
			// Strip inline comments before inspecting for motion / mode / G92,
			// so a comment containing "E..." cannot contaminate accounting.
			code := line
			if i := strings.IndexByte(code, ';'); i >= 0 {
				code = code[:i]
			}
			code = strings.TrimRight(code, " \t")
			if code == "" {
				continue
			}
			// Extrusion mode
			if code == "M82" {
				extMode = extAbsolute
				continue
			}
			if code == "M83" {
				extMode = extRelative
				continue
			}
			// G92 E reset
			if strings.HasPrefix(code, "G92") {
				if m := reG92E.FindStringSubmatch(code); m != nil {
					val, err := strconv.ParseFloat(m[1], 64)
					if err == nil {
						ePosition = val
					}
				}
				continue
			}
			// G0/G1/G2/G3 with E parameter
			if isMotionCommand(code) {
				if m := reEParam.FindStringSubmatch(code); m != nil {
					eVal, err := strconv.ParseFloat(m[1], 64)
					if err == nil {
						var delta float64
						if extMode == extRelative {
							delta = eVal
						} else {
							delta = eVal - ePosition
							ePosition = eVal
						}
						accumulator += delta
					}
				}
			}

		case stateFooter:
			parseFooterLine(line, &pf.Footer)
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("gcode: read: %w", err)
	}

	if !headerFound {
		return nil, fmt.Errorf("gcode: no HEADER_BLOCK_START found — unrecognised file format")
	}

	// Flush any remaining accumulator (truncated file)
	if state == stateStartup || state == stateLayer {
		flush()
	}

	// Determine status
	hasHeader := pf.Metadata.TotalLayers > 0 || pf.Metadata.SlicerName != ""
	hasConfig := pf.Config.FilamentType != ""
	hasFooter := pf.Footer.FilamentUsage.LengthMM > 0
	hasLayers := len(pf.Layers) > 0
	layersComplete := len(pf.Layers) == pf.Metadata.TotalLayers && pf.Metadata.TotalLayers > 0
	hasDiameter := pf.Metadata.FilamentDiameter > 0
	hasDensity := pf.Metadata.FilamentDensity > 0

	if hasHeader && hasConfig && hasLayers && hasFooter && layersComplete && hasDiameter && hasDensity {
		pf.Status = ParseOK
	} else {
		pf.Status = ParsePartial
	}

	return pf, nil
}

func isMotionCommand(line string) bool {
	tok := line
	if i := strings.IndexAny(tok, " \t"); i >= 0 {
		tok = tok[:i]
	}
	switch tok {
	case "G0", "G1", "G2", "G3":
		return true
	}
	return false
}

// unsupportedToolChange reports whether line selects a non-default tool
// (T1–T9). Multi-digit tokens such as Bambu's T1000 / T255 preset codes are
// explicitly allowed and return (_, false).
func unsupportedToolChange(line string) (string, bool) {
	tok := line
	if i := strings.IndexAny(tok, " \t"); i >= 0 {
		tok = tok[:i]
	}
	if len(tok) == 2 && tok[0] == 'T' && tok[1] >= '1' && tok[1] <= '9' {
		return tok, true
	}
	return "", false
}

func parseHeaderLine(line string, m *PrintMetadata) {
	// "; generated by OrcaSlicer 2.3.2 on 2026-04-20 at 22:17:12"
	if matches := reGeneratedBy.FindStringSubmatch(line); matches != nil {
		m.SlicerName = matches[1]
		m.SlicerVersion = matches[2]
		t, err := time.Parse("2006-01-02 at 15:04:05", matches[3])
		if err == nil {
			m.GeneratedAt = t
		}
		return
	}

	// "; model printing time: 1h 38m 19s; total estimated time: 1h 44m 35s"
	const modelTimePrefix = "; model printing time: "
	const totalTimeKey = "; total estimated time: "
	if strings.HasPrefix(line, modelTimePrefix) {
		parts := strings.SplitN(line, totalTimeKey, 2)
		modelStr := strings.TrimPrefix(parts[0], modelTimePrefix)
		if d, err := parseDuration(modelStr); err == nil {
			m.ModelPrintTime = d
		}
		if len(parts) == 2 {
			if d, err := parseDuration(parts[1]); err == nil {
				m.TotalEstimatedTime = d
			}
		}
		return
	}

	// "; estimated first layer printing time (normal mode) = 6m 15s"
	const firstLayerPrefix = "; estimated first layer printing time (normal mode) = "
	if strings.HasPrefix(line, firstLayerPrefix) {
		val := strings.TrimPrefix(line, firstLayerPrefix)
		if d, err := parseDuration(val); err == nil {
			m.FirstLayerTime = d
		}
		return
	}

	// Key: value lines
	if !strings.HasPrefix(line, "; ") {
		return
	}
	rest := line[2:]
	idx := strings.Index(rest, ": ")
	if idx < 0 {
		return
	}
	key := rest[:idx]
	val := strings.TrimSpace(rest[idx+2:])

	switch key {
	case "total layer number":
		if n, err := strconv.Atoi(val); err == nil {
			m.TotalLayers = n
		}
	case "filament_density":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			m.FilamentDensity = f
		}
	case "filament_diameter":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			m.FilamentDiameter = f
		}
	case "max_z_height":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			m.MaxZHeight = f
		}
	}
}

func parseConfigLine(line string, c *PrintConfig) error {
	if !strings.HasPrefix(line, "; ") {
		return nil
	}
	rest := line[2:]
	idx := strings.Index(rest, " = ")
	if idx < 0 {
		return nil
	}
	key := rest[:idx]
	val := strings.TrimSpace(rest[idx+3:])

	// Multi-filament detection: any filament-scoped config key whose value is
	// a per-tool semicolon-separated list is unsupported in v1. Quoted values
	// (gcode snippets like filament_start_gcode) can legitimately contain ';'
	// and are excluded from the check.
	if strings.HasPrefix(key, "filament_") && !strings.HasPrefix(val, `"`) && strings.Contains(val, ";") {
		return fmt.Errorf("gcode: multi-filament file not supported (field %q has multiple values: %q)", key, val)
	}

	// Match longest key first to avoid nozzle_temperature matching nozzle_temperature_initial_layer
	switch key {
	case "nozzle_temperature_initial_layer":
		if n, err := strconv.Atoi(val); err == nil {
			c.NozzleInitialLayerTemp = n
		}
	case "nozzle_temperature":
		if n, err := strconv.Atoi(val); err == nil {
			c.NozzleTemp = n
		}
	case "filament_type":
		c.FilamentType = val
	case "filament_colour":
		c.FilamentColour = val
	case "filament_vendor":
		c.FilamentVendor = val
	}
	return nil
}

func parseFooterLine(line string, f *FooterSummary) {
	if !strings.HasPrefix(line, "; ") {
		return
	}
	rest := line[2:]
	idx := strings.Index(rest, " = ")
	if idx < 0 {
		return
	}
	key := rest[:idx]
	val := strings.TrimSpace(rest[idx+3:])

	switch key {
	case "filament used [mm]":
		if f64, err := strconv.ParseFloat(val, 64); err == nil {
			f.FilamentUsage.LengthMM = f64
		}
	case "filament used [cm3]":
		if f64, err := strconv.ParseFloat(val, 64); err == nil {
			f.FilamentUsage.VolumeCM3 = f64
		}
	case "filament used [g]":
		if f64, err := strconv.ParseFloat(val, 64); err == nil {
			f.FilamentUsage.WeightG = f64
		}
	case "filament cost":
		if f64, err := strconv.ParseFloat(val, 64); err == nil {
			f.FilamentCost = f64
		}
	}
}

func convertToFilamentUsage(lengthMM, diameter, density float64) FilamentUsage {
	if diameter <= 0 {
		return FilamentUsage{LengthMM: lengthMM}
	}
	radius := diameter / 2
	crossSection := math.Pi * radius * radius // mm²
	volumeMM3 := lengthMM * crossSection
	volumeCM3 := volumeMM3 / 1000
	var weightG float64
	if density > 0 {
		weightG = volumeCM3 * density
	}
	return FilamentUsage{
		LengthMM:  lengthMM,
		VolumeCM3: volumeCM3,
		WeightG:   weightG,
	}
}

func parseDuration(s string) (time.Duration, error) {
	s = strings.ReplaceAll(s, " ", "")
	return time.ParseDuration(s)
}
